### ISSUE TITLE
Composer fails for Laravel 6.0.4

### ISSUE THREAD

**Issue by Furburger** [spinen/laravel-quickbooks-client#10]
Not sure why it is trying to uninstall laravel/framework v6.0.4 when I run composer? Your composer.json seems to cater for ver 6.0.*. Any ideas?

**c:\\my-dir>composer require spinen/laravel-quickbooks-client**

Using version ^3.0 for spinen/laravel-quickbooks-client
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
    - Conclusion: remove laravel/framework v6.0.4
    - Conclusion: don't install laravel/framework v6.0.4
    - spinen/laravel-quickbooks-client 3.0.0 requires illuminate/routing 5.5.*|5.6.*|5.7.*|5.8.*

- don't install illuminate/routing 5.5.x-dev|don't install laravel/framework v6.0.4
    - don't install illuminate/routing 5.6.x-dev|don't install laravel/framework v6.0.4
    - don't install illuminate/routing 5.7.17|don't install laravel/framework v6.0.4
    - don't install illuminate/routing 5.7.18|don't install laravel/framework v6.0.4
    - don't install illuminate/routing 5.7.19|don't install laravel/framework v6.0.4
    - don't install illuminate/routing 5.7.x-dev|don't install laravel/framework v6.0.4
    - don't install illuminate/routing 5.8.x-dev|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.5.0|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.5.16|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.5.17|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.5.2|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.5.28|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.5.33|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.5.34|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.5.35|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.5.36|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.5.37|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.5.39|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.5.40|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.5.41|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.5.43|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.5.44|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.0|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.1|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.10|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.11|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.12|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.13|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.14|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.15|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.16|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.17|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.19|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.2|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.20|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.21|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.22|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.23|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.24|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.25|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.26|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.27|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.28|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.29|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.3|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.30|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.31|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.32|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.33|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.34|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.35|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.36|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.37|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.38|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.39|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.4|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.5|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.6|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.7|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.8|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.6.9|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.7.0|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.7.1|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.7.10|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.7.11|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.7.15|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.7.2|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.7.20|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.7.21|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.7.22|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.7.23|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.7.26|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.7.27|don't install laravel/framework v6.0.4
    - don't install illuminate/routing v5.7.28|don't install laravel/framework v6.0.4

Installation failed, reverting ./composer.json to its original content.

**Comment by jimmypuckett** [comment]
@Furburger Thanks for reporting this issue.  It appears that the `composer.json` in the `3.0.0` & `3.0.1` releases are not allowing version 6 of Laravel.  However, the branches show that they are.  I am going to loop in @ssfinney to have him look into his with me.

@ssfinney Do you know why the tagged releases are different than the branches?

**Comment by ssfinney** [comment]
@jimmypuckett @Furburger Yep, found the problem. When you tag a release off of the `develop` branch, packagist considers it a pre-release tag. Packagist tagged the repo at "3.0.1.x-dev" instead of a production "3.0.1".

Tagging the release on the master branch solves this. I have pushed 3.0.2 which correctly allows Laravel 6.0.*

**Comment by ssfinney** [comment]
@Furburger Thanks for bringing this up! Let us know if this persists and we'll keep digging.

**Comment by Furburger** [comment]
Hi

It looks like the  illuminate/routing dependency also needs to be changed to accept 6.0*

I get this message now...

spinen/laravel-quickbooks-client 3.0.0 requires illuminate/routing 5.5.*|5.6.*|5.7.*|5.8.*

It may have to be done for the other dependencies as well:

illuminate/database
illuminate/http

**Comment by jimmypuckett** [comment]
So, they released version 6.1 of the Illuminate packages yesterday.  We are not accustomed to Laravel being on semver, so our package was too restrictive.

Anyhow, we just pushed up a new tagged version.

Please let us know if that does not work for you.
