### ISSUE TITLE
Auto Discovery not working

### ISSUE THREAD

**Issue by Furburger** [spinen/laravel-quickbooks-client#11]
I am not a Laravel expert, so I may be doing something totally stupid, but I would appreciate some help. I could not get this package to work on Laravel 6.04, so I tried it on an existing Laravel 5.8 project.

Composer installs fine, but afterwards, none of the Spinen/QuickBooks Service Providers and Middleware or Migrations are added. 

After running 

c:\\my-project>**composer require spinen/laravel-quickbooks-client**

It installs all the files 

- Installing quickbooks/v3-php-sdk (dev-master f94ac9e): Cloning f94ac9ed63 from cache
- Installing spinen/laravel-quickbooks-client (3.0.1): Downloading (100%)
- Installing beyondcode/laravel-dump-server (1.3.0): Downloading (100%)

................ etc

**IT THEN DOES ITS AUTO DISCOVERY....**

Writing lock file
Generating optimized autoload files

> @php artisan package:discover --ansi
Discovered Package: beyondcode/laravel-dump-server
Discovered Package: spinen/laravel-quickbooks-client

..... etc

Package manifest generated successfully.
Generated optimized autoload files containing 4094 classes

When I look at my project, however,none of the Service Providers and Middleware or Migrations are added to the project.

Any ideas?

**Comment by jimmypuckett** [comment]
So, I just downloaded a fresh 5.8 & did a composer install without any issues...

```php
$ cd laravel-5.8
$ composer require spinen/laravel-quickbooks-client
Using version ^3.0 for spinen/laravel-quickbooks-client
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 82 installs, 0 updates, 0 removals
 // Removed all the installs to make shorter...
symfony/routing suggests installing symfony/config (For using the all-in-one router or any loader)
symfony/routing suggests installing symfony/yaml (For using the YAML loader)
symfony/routing suggests installing symfony/expression-language (For using expression matching)
symfony/routing suggests installing doctrine/annotations (For using the annotation loader)
symfony/event-dispatcher-contracts suggests installing psr/event-dispatcher
symfony/event-dispatcher suggests installing symfony/dependency-injection
symfony/http-kernel suggests installing symfony/browser-kit
symfony/http-kernel suggests installing symfony/config
symfony/http-kernel suggests installing symfony/dependency-injection
symfony/service-contracts suggests installing symfony/service-implementation
symfony/console suggests installing symfony/lock
swiftmailer/swiftmailer suggests installing true/punycode (Needed to support internationalized email addresses, if ext-intl is not installed)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
ramsey/uuid suggests installing ircmaxell/random-lib (Provides RandomLib for use with the RandomLibAdapter)
ramsey/uuid suggests installing ext-libsodium (Provides the PECL libsodium extension for use with the SodiumRandomGenerator)
ramsey/uuid suggests installing ext-uuid (Provides the PECL UUID extension for use with the PeclUuidTimeGenerator and PeclUuidRandomGenerator)
ramsey/uuid suggests installing moontoast/math (Provides support for converting UUID to 128-bit integer (in string form).)
ramsey/uuid suggests installing ramsey/uuid-doctrine (Allows the use of Ramsey\Uuid\Uuid as Doctrine field type.)
ramsey/uuid suggests installing ramsey/uuid-console (A console application for generating UUIDs with ramsey/uuid)
symfony/translation suggests installing symfony/config
symfony/translation suggests installing symfony/yaml
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
league/flysystem suggests installing league/flysystem-eventable-filesystem (Allows you to use EventableFilesystem)
league/flysystem suggests installing league/flysystem-rackspace (Allows you to use Rackspace Cloud Files)
league/flysystem suggests installing league/flysystem-azure (Allows you to use Windows Azure Blob storage)
league/flysystem suggests installing league/flysystem-webdav (Allows you to use WebDAV storage)
league/flysystem suggests installing league/flysystem-aws-s3-v2 (Allows you to use S3 storage with AWS SDK v2)
league/flysystem suggests installing league/flysystem-aws-s3-v3 (Allows you to use S3 storage with AWS SDK v3)
league/flysystem suggests installing spatie/flysystem-dropbox (Allows you to use Dropbox storage)
league/flysystem suggests installing srmklive/flysystem-dropbox-v2 (Allows you to use Dropbox storage for PHP 5 applications)
league/flysystem suggests installing league/flysystem-cached-adapter (Flysystem adapter decorator for metadata caching)
league/flysystem suggests installing league/flysystem-sftp (Allows you to use SFTP server storage via phpseclib)
league/flysystem suggests installing league/flysystem-ziparchive (Allows you to use ZipArchive adapter)
laravel/framework suggests installing aws/aws-sdk-php (Required to use the SQS queue driver and SES mail driver (^3.0).)
laravel/framework suggests installing doctrine/dbal (Required to rename columns and drop SQLite columns (^2.6).)
laravel/framework suggests installing guzzlehttp/guzzle (Required to use the Mailgun and Mandrill mail drivers and the ping methods on schedules (^6.0).)
laravel/framework suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 driver (^1.0).)
laravel/framework suggests installing league/flysystem-cached-adapter (Required to use the Flysystem cache (^1.0).)
laravel/framework suggests installing league/flysystem-rackspace (Required to use the Flysystem Rackspace driver (^1.0).)
laravel/framework suggests installing league/flysystem-sftp (Required to use the Flysystem SFTP driver (^1.0).)
laravel/framework suggests installing moontoast/math (Required to use ordered UUIDs (^1.1).)
laravel/framework suggests installing nexmo/client (Required to use the Nexmo transport (^1.0).)
laravel/framework suggests installing pda/pheanstalk (Required to use the beanstalk queue driver (^4.0).)
laravel/framework suggests installing predis/predis (Required to use the redis cache and queue drivers (^1.0).)
laravel/framework suggests installing pusher/pusher-php-server (Required to use the Pusher broadcast driver (^3.0).)
laravel/framework suggests installing symfony/dom-crawler (Required to use most of the crawler integration testing tools (^4.2).)
laravel/framework suggests installing symfony/psr-http-message-bridge (Required to use PSR-7 bridging features (^1.1).)
laravel/framework suggests installing wildbit/swiftmailer-postmark (Required to use Postmark mail driver (^3.0).)
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
psy/psysh suggests installing hoa/console (A pure PHP readline implementation. You'll want this if your PHP install doesn't already support readline or libedit.)
quickbooks/v3-php-sdk suggests installing guzzlehttp/guzzle (Uses Guzzle to make HTTP Requests)
filp/whoops suggests installing whoops/soap (Formats errors as SOAP responses)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.6.0)
phpunit/phpunit suggests installing phpunit/php-invoker (^2.0)
phpunit/phpunit suggests installing ext-xdebug (*)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: beyondcode/laravel-dump-server
Discovered Package: fideloper/proxy
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: spinen/laravel-quickbooks-client
Package manifest generated successfully.
$
```

I am using a Mac & it looks like you maybe on a Windows computer, so there maybe some issue on Windows that I cannot test?

**Comment by jimmypuckett** [comment]
@ssfinney Do you have any ideas on this one?

**Comment by Furburger** [comment]
Hi

Thanks for going to all the trouble. Much appreciated.

When you do the above, do you see the spinen/laravel-quickbooks-client Service Providers, Middleware and Migration? 

See this Article:

https://stackoverflow.com/questions/46877662/laravel-5-5-autodiscovery-not-registering

It says: 
"Package discovery does not publish a package's assets, such as the configuration file you describe. The developer must explicitly run the vendor:publish command. Eg:

php artisan vendor:publish --provider='Spatie\Backup\BackupServiceProvider'

This limitation is by design. Laravel has no way to know if the developer wants to publish a package's components, because, in many cases, packages provide optional components and the developer can choose which ones to publish."

And here is a full explanation of the Package Auto Discovery process (which I am sure you are familiar with but it may be useful).

https://divinglaravel.com/laravels-package-auto-discovery


I have installed other packages before and they have auto discovered fine so I am not sure what is going on. I doubt it is a Windows thing -  we have less security lock downs than Mac OS.

Anyway, I can always cut & paste them from Github and manually insert them into my project, but I was just wondering why it didn't work.

**Comment by Furburger** [comment]
I noticed that if I run this:

> php artisan vendor:publish

 Which provider or tag's files would you like to publish?:
  [0 ] Publish files from all providers and tags listed below
  [1 ] Provider: BeyondCode\DumpServer\DumpServerServiceProvider
  [2 ] Provider: Fideloper\Proxy\TrustedProxyServiceProvider
  [3 ] Provider: Illuminate\Foundation\Providers\FoundationServiceProvider
  [4 ] Provider: Illuminate\Mail\MailServiceProvider
  [5 ] Provider: Illuminate\Notifications\NotificationServiceProvider     
  [6 ] Provider: Illuminate\Pagination\PaginationServiceProvider
  [7 ] Provider: Laravel\Tinker\TinkerServiceProvider
  [8 ] Provider: Spinen\QuickBooks\Providers\ServiceProvider
  [9 ] Provider: Yajra\DataTables\DataTablesServiceProvider
  [10] Tag: config
  [11] Tag: datatables
  [12] Tag: laravel-errors
  [13] Tag: laravel-mail
  [14] Tag: laravel-notifications
  [15] Tag: laravel-pagination
  [16] Tag: quickbooks-config
  [17] Tag: quickbooks-migrations
  [18] Tag: quickbooks-views

If I choose option [8] it says this:

Copied Directory [\vendor\spinen\laravel-quickbooks-client\database\migrations] To [\database\migrations]
Copied Directory [\vendor\spinen\laravel-quickbooks-client\resources\views] To [\resources\views\vendor\quickbooks]
Publishing complete

**Comment by jimmypuckett** [comment]
@Furburger On step 2 of the configuration in the readme...

https://github.com/spinen/laravel-quickbooks-client#configuration

we get into the publishing of the vendor assets.

The default config, makes assumptions that generally meet your needs, so you only have to set up the env's per step 1.

I am glad that you found the vendor publish stuff.

@ssfinney are going to look into that team version issue with Laravel 6.

Thanks.

**Comment by jimmypuckett** [comment]
I am going to close this as it appears that everything is working out for you, but please feel free to reopen if needed.
