### ISSUE TITLE
After connecting, receive "Class 'Alert' not found"

### ISSUE THREAD

**Issue by PlaidFoxSG** [spinen/laravel-quickbooks-client#12]
On Controller.php line 89.

Not sure what is supposed to be referenced here.  I'm running L6, if that helps.

**Comment by jimmypuckett** [comment]
@PlaidFoxSG This is an odd issue.  For some reason, we have a hidden dependency. In the internal app the we use this package, we have another package that does alerts `uxweb/sweet-alert`, so when we extracted out this package, we did not catch that we have that dependency.

I am not sure how if is missed with the other users?

Anyhow, I am not sure that we want to include it in this package or refector the message?

For now, can you require that package & see if you error goes away?

I am sorry for the delay in responding to you.  I have been out of town & then missed this issue.

**Comment by PlaidFoxSG** [comment]
hey.  yea, after some searching, I figured you had used sweet-alert.  However, I didn't want to add the extra dependency, so I edited your code and replaced it with a simple session()->flash(), assuming that the next round you might fix this, and then all would be good.

**Comment by amirshawn** [comment]
Hi,
Thank you for making this package!  I was wondering if you'll be fixing this soon?  I use Envoyer so even if I fix this on my local site, the original code is pushed to my production site.  
Thank you

**Comment by ssfinney** [comment]
Hi @amirshawn! I'm giving the above PR a shot at removing that dependency for you and @PlaidFoxSG by flashing the message straight from the redirect. @jimmypuckett can review and give feedback.

Thanks for following up!
