### ISSUE TITLE
Laravel 6 migrations

### ISSUE THREAD

**Issue by sahamilton** [spinen/laravel-quickbooks-client#14]
For Laravel 6 the CreateQuickBooksTokenTable needs to be update.  
Change line 18 from 
` $table->unsignedInteger('user_id');`
to
` $table->unsignedBigInteger('user_id');`

**Comment by ssfinney** [comment]
Thanks @sahamilton!

@jimmypuckett The issue with doing this is we would have to pin our package to >Laravel 5.8. Do you think we should just change the composer.json to `~5.8|~6|~7` instead of 5.5?

**Comment by sahamilton** [comment]
My personal opinion is that > 5.5 is fine as 5.5 support ends this year per docs


Version

Release

Bug Fixes Until

Security Fixes Until


5.5 (LTS)

August 30th, 2017

August 30th, 2019

August 30th, 2020

 

However the end user fix is relatively simple … just modify the migration mnaually

**Comment by jimmypuckett** [comment]
Ya, I am going to dig into this now to see if we can make the migration "smart" to know when to use either.

**Comment by sahamilton** [comment]
Jimmy

That would be cool … though it’s a pretty simple change that the user can make one time.  

 

Stephen

**Comment by jimmypuckett** [comment]
@ssfinney & @sahamilton Check out #20 to see what you think
