### ISSUE TITLE
Use a different model for tokens

### ISSUE THREAD

**Issue by atymic** [spinen/laravel-quickbooks-client#15]
For example, save auth against a `Company` model rather than a user, allowing multiple users to access the same connection.

Will fork and PR.

**Comment by Dozorov** [comment]
I need it too...

**Comment by jimmypuckett** [comment]
@atymic Did you get anywhere on that PR?

**Comment by ViktorIvanisenko** [comment]
I took your module as an example of functionality, I want to implement the connection of multiple users in turn with different accounts.

**Comment by atymic** [comment]
I ended up just taking the quickbooks token class and not using the package. 
I can PR if you'd like, but it would be a breaking release since it's very different to how it work rn.

**Comment by ViktorIvanisenko** [comment]
> I ended up just taking the quickbooks token class and not using the package.
> I can PR if you'd like, but it would be a breaking release since it's very different to how it work rn.

I also redesigned the token class and the client class. I take access to QuickBooks from the company tables.

**Comment by atymic** [comment]
Yep, that's how I did it.

**Comment by ViktorIvanisenko** [comment]
> Yep, that's how I did it.

When I'm done, I'll show you the code.

**Comment by hyphen81** [comment]
@ViktorIvanisenko Would love to see an example of how you did this. I think I need this approach too.

**Comment by ssfinney** [comment]
This sounds like a great potential new feature. Example code is welcome.
