### ISSUE TITLE
Laravel v7 NOT NULL constraint error

### ISSUE THREAD

**Issue by Yiddishe-Kop** [spinen/laravel-quickbooks-client#26]
I just installed your package in a Laravel 7 application.

After connecting to Quickbooks, and saving the token I get this error:
```
[2020-05-19 11:51:00] local.ERROR: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: quickbooks_tokens.id (SQL: insert into "quickbooks_tokens" ("user_id", "access_token", "access_token_expires_at", "realm_id", "refresh_token", "refresh_token_expires_at", "updated_at", "created_at") values (1,...)
```

I managed to fix it by editing the "quickbooks_tokens" migration file - the "id" column from this:
`$table->unsignedBigInteger('id');`
to this:
`$table->id();`

Should I create a pull request?
Or publishing the vendor-migrations in my project should suffice?

**Comment by jimmypuckett** [comment]
I don't see how those two items would be connected.  The standard is to use unsigned id as it gives you `18446744073709551615` vs `9223372036854775807`, so don't want to make it signed.

In looking at the SQL that you have...

```sql
insert into "quickbooks_tokens"
    ("user_id", "access_token", "access_token_expires_at", "realm_id", "refresh_token", "refresh_token_expires_at", "updated_at", "created_at")
values (1,...)
```

I wonder is the `...` is what was sent or just masked out?

If you can find more information about the issue, please update this & we will iron it out, but it sounds like it is something other than the `id` type.

**Comment by Yiddishe-Kop** [comment]
@jimmypuckett kudos for the fast reply!

I just masked out the data...

The error seemed to be that when creating a new token, it didn't have an id, which is required.
After changing the id column to a native `id` type, I understand that Laravel auto assigns the ID.

**Comment by jimmypuckett** [comment]
@ssfinney Do you have any suggestions on this?

**Comment by ssfinney** [comment]
@jimmypuckett Yep: https://laravel.com/docs/7.x/migrations#creating-columns

We were using `$table->unsignedBigInteger('id');` but that disables Laravel's auto-incrementing feature and breaks stuff.

We should be doing this: `$table->bigIncrements('id');` which keeps the auto-incrementing.
The reason @Yiddishe-Kop's change worked is because `$table->id();` is an alias of `$table->bigIncrements('id');` in Laravel 7+.

**Comment by jimmypuckett** [comment]
argh, I cannot believe I missed that.

thanks @ssfinney

**Comment by ssfinney** [comment]
Tagged @ 4.0.2
