### ISSUE TITLE
Refresh OAuth 2 Access token with Refresh Token failed

### ISSUE THREAD

**Issue by mishabachkur** [spinen/laravel-quickbooks-client#27]
I often get this error - Refresh OAuth 2 Access token with Refresh Token failed. Body: [{\"error\":\"invalid_grant\"}]

**Comment by ssfinney** [comment]
Hi @mishabachkur! Unfortuntely there are several reasons that you might get an `invalid_grant` response. There are a few online threads that give some solutions to this, including this one: https://help.developer.intuit.com/s/question/0D50f00006XhESaCAN/always-getting-invalidgrant-when-refreshing-access-token

At the bottom, someone posted this:
"I had a similar issue and was addressed by two things, one is making sure refreshing the (access) token is only done when it has expired (not calling it multiple times). Two, this I suspect some people may miss reading on the documentation, refreshing the access token can also return a new RefreshToken, make sure to use the new one for subsequent refresh calls."

**Comment by ssfinney** [comment]
@jimmypuckett Anything to add to this?

**Comment by ssfinney** [comment]
@mishabachkur Closing this but feel free to reply if you are still stuck!
