### ISSUE TITLE
quickBooksToken does not exist

### ISSUE THREAD

**Issue by joelgomezb** [spinen/laravel-quickbooks-client#3]
Laravel 5.7

Auth::logInUsingId(1)
App\User {#2894
     id: 1,
     name: "Joel Gomez",
     email: "joelgomezb@gmail.com",
     created_at: "2018-08-19 16:35:35",
     updated_at: "2018-08-19 16:35:35",
     quickBooksToken: null,

$quickbooks = app('QuickBooks')
BadMethodCallException with message 'Method Illuminate/Database/Query/Builder::quickBooksToken does not exist.'

Model:
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spinen\QuickBooks\Laravel\HasQuickBooksToken as QuickBooks;

class User extends Authenticatable
{

**Comment by jimmypuckett** [comment]
@joelgomezb I am not sure why you are having this issue.  Can you post up your user model?
