### ISSUE TITLE
invalid_grant

### ISSUE THREAD

**Issue by rtaylor82** [spinen/laravel-quickbooks-client#46]
I have a user getting: 
```
QuickBooksOnline\API\Exception\ServiceException
Refresh OAuth 2 Access token with Refresh Token failed. Body: [{"error":"invalid_grant"}].
```

While other users continue to connect without issue. 

This is the example database row stored when issue happens: 
<img width="1058" alt="Screen Shot 2021-07-01 at 2 12 17 PM" src="https://user-images.githubusercontent.com/6969996/124171295-5e6b0480-da76-11eb-8080-03e5bd568c60.png">

As referenced in the thread response by @ssfinney on  #27 

Could it be caused by calling "$qbClient = app('Spinen\QuickBooks\Client');" in multiple tabs/sessions?

> I had a similar issue and was addressed by two things, one is making sure refreshing the (access) token is only done when it has expired (not calling it multiple times). Two, this I suspect some people may miss reading on the documentation, refreshing the access token can also return a new RefreshToken, make sure to use the new one for subsequent refresh calls.
> 
>  
> 
> Pasted from the doc:
> 
> Even though the refresh token is valid for 100 days, the value of refresh token can change every 24-26 hour period. Hence, you might encounter a situation where the request token that you received first is different than the latest one. As a best practice, always store the latest refresh token received from the API response and use that to make subsequent calls to obtain a new pair of tokens.
> 
>  
> 
> Also an additional note, some care must be taken when refreshing, making sure it does not get called multiple times (from differing sessions, etc). I used a static/class object to indicate.
> 
>  
> 
> Hope this helps to some weary developer :-)

**Comment by rtaylor82** [comment]
Actually, it appears to happen when both users are admin and when one user connects to QB it requests to 'Change Admin'.  Upon doing that, the other user then gets the error: 

> QuickBooksOnline\API\Exception\ServiceException
Refresh OAuth 2 Access token with Refresh Token failed. Body: [{"error":"invalid_grant"}]. (View: 

I'm assuming this is caused by both users being admins and I need to look into setting different permissions for them on the QBO side of things...

**Comment by jimmypuckett** [comment]
@rtaylor82 Is there an action item for us at this time?

**Comment by rtaylor82** [comment]
No sir, on QBO end. Thanks, closing
