### ISSUE TITLE
Redirect URI 

### ISSUE THREAD

**Issue by kenneth-ip** [spinen/laravel-quickbooks-client#47]
Would you mind to kindly show us how to write the redirect URI or callback with your package?

**Comment by rtaylor82** [comment]
The URI is set in the quickbooks.php file in the config/ directory of your project. 

By default it would be: <siteurl>/quickbooks/token

<img width="849" alt="Screen Shot 2021-07-06 at 10 27 43 AM" src="https://user-images.githubusercontent.com/6969996/124617503-fa18be00-de44-11eb-8507-8e23c2619114.png">

**Comment by jimmypuckett** [comment]
@rtaylor82 Thanks for pitching in & helping.

@kenneth-ip I am closing this.
