### ISSUE TITLE
Connecting to Multiple QBO Accounts.

### ISSUE THREAD

**Issue by ezea213** [spinen/laravel-quickbooks-client#48]
Im having issues, My App needs to be connected to multiple QBO Accounts. The problem is, when my **App User A** is connected to **QBO Account A** then another "App User" connects to another (like **QBO Account B**). **App User A** will lose its connection to QBO. I followed the configuration as exampled. Thanks.

**Comment by ssfinney** [comment]
@ezea213 Yeah, great catch. We've noticed that in our app as well. It's a known issue. One day we could add this as a new feature, but our bandwidth to work on this right now is low. PRs are welcome.

**Comment by jimmypuckett** [comment]
Tied to #15 ?
