### ISSUE TITLE
Laravel 9 not supported

### ISSUE THREAD

**Issue by palashcn** [spinen/laravel-quickbooks-client#51]
Hi,

Can you please make it working for Laravel 9?

Thanks

**Comment by rahulkumarcn** [comment]
<img width="851" alt="image" src="https://user-images.githubusercontent.com/97872472/156540677-729f6547-f060-4e03-af6f-4fb04766fac8.png">

**Comment by shawnreid** [comment]
**Use at own risk** but if anyone is looking to upgrade I created a fork.

Place the following in your composer.json

```
"repositories": [{
    "type": "vcs",
    "url": "https://github.com/shawnreid/laravel-quickbooks-client",
    "no-api": true
}],
"require": {
    "spinen/laravel-quickbooks-client": "dev-develop",
},
```

**Comment by asadmu92** [comment]
not able to connect the app getting QuickBooksOnline\API\Exception\SdkException with message 'Please Setup Service Context before making get CompanyInfo call error
