### ISSUE TITLE
Exception on getting company info

### ISSUE THREAD

**Issue by naonak** [spinen/laravel-quickbooks-client#8]
Hi

I tried to apply usage example of readme of this gist repo but I got this error message 💯 

QuickBooksOnline/API/Exception/SdkException with message 'Please Setup Service Context before making get CompanyInfo call.'

What I am missing ? Thanks for your help

**Comment by jimmypuckett** [comment]
@naonak I have never seen that error before.  In reviewing the QBO SDK, the error is from here...

https://github.com/intuit/QuickBooks-V3-PHP-SDK/blob/01906e33c31c4a71fae659ebac0f37b6b871f51e/src/DataService/DataService.php#L1619

which means that the `serviceContext` is empty or the `realmId` n the `serviceContext` is empty.

Can you please post up...

1) Some of your code where you are using the class
2) The entire stack trace
3) Output from `config('services.connectwise')` --NOTE: Mask out the sensitive values. Really mask all values, just want to see that the values are set.

**Comment by jimmypuckett** [comment]
I am closing this as it is abandoned.  @naonak If you would like help, please feel free to reopen.

**Comment by PlaidFoxSG** [comment]
I got this same error.  After a lot of digging, it came to my attention that you need to "connect" first, which was not clear in the documentation.  It might be a good idea to clarify that you have to go through the "/quickbooks/connect" first with that user before being able to run any commands.

**Comment by jimmypuckett** [comment]
@ssfinney What would you like to do with this?

**Comment by ssfinney** [comment]
here's what's in the docs. Do we need to add a line for going to the `/quickbooks/connect` route? Right after the `Auth::logInUsingId(1)` call?

```php
php artisan tinker
Psy Shell v0.8.17 (PHP 7.1.14 — cli) by Justin Hileman
>>> Auth::logInUsingId(1)
=> App\User {#1668
     id: 1,
     // Other keys removed for example
   }
>>> $quickbooks = app('Spinen\QuickBooks\Client') // or app('QuickBooks')
=> Spinen\QuickBooks\Client {#1613}
>>> $quickbooks->getDataService()->getCompanyInfo();
=> QuickBooksOnline\API\Data\IPPCompanyInfo {#1673
     +CompanyName: "Sandbox Company_US_1",
     +LegalName: "Sandbox Company_US_1",
     // Other properties removed for example
   }
>>>
```

**Comment by kusmayadi** [comment]
I got the same error:

`QuickBooksOnline\API\Exception\SdkException
Please Setup Service Context before making get CompanyInfo call.`

**Comment by misoy** [comment]
I got the same error. How to fix this?

`QuickBooksOnline\API\Exception\SdkException Please Setup Service Context before making get CompanyInfo call.`

**Comment by ssfinney** [comment]
Hey everyone! While we work on updating the docs, try making sure you are making a call to the connection route (by default, `/quickbooks/connect`) to get your Access Token before making calls to Quickbooks.

**Comment by ssfinney** [comment]
Closing this unless someone still is having a problem after using the connection route (see above comment). Just let me know if you still have an issue.

**Comment by RizaHKhan** [comment]
Quick follow up on this. I'm a noob so sorry for the really low level question here but how do you make a call to the connection route in Tinker? I don't think the README has been updated per this discussion.

Thank you!

**Comment by ssfinney** [comment]
@RizaHKhan Before using tinker, log in to your Laravel app and go to the connection route *first* so that that your user can get a token from Quickbooks. Then, in tinker your commands should work.

**Comment by korcstar** [comment]
I had same issue when use accessToken created by me manually
It was gone after I set realmid to accesstoken

```
$accessToken = new OAuth2AccessToken($clientID, $clientSecret, $accessTokenString, $refreshTokenString);
$accessToken->setRealmId($company_id);
```

**Comment by ghost** [comment]
> OAuth2AccessToken

How can call connection route first. Can you explain I am not getting.
[https://prnt.sc/SZTsfe5pE0nt](url)

**Comment by asadmughal92** [comment]
i am getting this error what is the issue and also I need just apis no frontend can you guide me
![image](https://user-images.githubusercontent.com/25720024/205820438-3b628a7d-6d34-42e8-ae06-7b5f20ed33b0.png)

**Comment by jimmypuckett** [comment]
@asadmu92 The API with QBO is not intended to be "headless".  You have to interact with their authentication service via their GUI to be given a token back.
